// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqyazbzxsibfarxpvarh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxeWF6Ynp4c2liZmFyeHB2YXJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyOTI0MjksImV4cCI6MjA3Njg2ODQyOX0.NLcFi0XJOOUrlwzFjLGlZ2La15YOcs4sxTcD0fbCUTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});